### ISSUE TITLE
Observability Prediction

### ISSUE THREAD

**Issue by KlemensFroehlich** [MannLabs/alphapeptdeep#105]
Dear Developers
I am new to the Alpha Environment and have recently come across a project in which I have to select peptides for targeted detection.
Does your framework provide the possibility to predict relative ionization efficiency (MS1 intensity) between peptides or could it be trained to do that? Or is there another resource that you can recommend? d::POP, PeptideRank, PREGO, MaxDB manual selection, PeptideProphet manual selection are all not really satisfying when I compare them to real life data.

Any help / insight would be appreciated!

Best Klemens

**Comment by jalew188** [comment]
If you have training data, you can easily do it by yourself.
