### ISSUE TITLE
How does "matched_intensity_df" from ModelManager.train_ms2_model (pretrain_model.py) look like?

### ISSUE THREAD

**Issue by HojunYou** [MannLabs/alphapeptdeep#113]
Hello, thanks for such a useful package!

I've been trying to fine-tune ms2_model from ModelManager object, but I'm having hard time figuring out how "matched_intensity_df" data frame looks like. 
Could you describe the structure of the data frame? or provide a sample. Thank you so much!

**Comment by jalew188** [comment]
Please check https://github.com/MannLabs/alphapeptdeep/blob/main/nbdev_nbs/psm_frag_reader/psmlabel_reader.ipynb and https://github.com/MannLabs/alphapeptdeep/blob/main/nbdev_nbs/psm_frag_reader/maxquant_frag_reader.ipynb
