### ISSUE TITLE
ValueError: need at most 63 handles, got a sequence of length 102

### ISSUE THREAD

**Issue by Maithy15** [MannLabs/alphapeptdeep#115]
Hi,

I get "ValueError: need at most 63 handles, got a sequence of length 102" when using the old version V1.0.2. Has this been fixed in the new version? I have to check again but I think I only get this error in our analysis computer. 

![image](https://github.com/MannLabs/alphapeptdeep/assets/78071837/4fa30ded-205b-4d08-94a7-6e3a3d243fef)

Thanks
Maithy

**Comment by jalew188** [comment]
This is the bug of python itself. Reducing the thread num to <= 60 may address this issue

**Comment by jalew188** [comment]
I will set thread num to <= 60 in the GUI and other settings.
