### ISSUE TITLE
Is it possible to get 1/K0 mobility instead of CCS from AlpahPept CCS predictions?

### ISSUE THREAD

**Issue by KarlClauser** [MannLabs/alphapeptdeep#116]
I am using the AlphaPept_ccs predictor through the Koina server.
https://koina.proteomicsdb.org/docs/#post-/AlphaPept_ccs_generic/infer

The only described output is 'ccs'. I am seeking to compare the predictions with measured ion mobilities in units of 1/K0 from our Bruker timsTOF SCP instrument. Is there an undocumented option to get the output directly as 1/K0? Or do I need to do that myself?

The following sentence is in the methods section of your paper Zeng et al NatComm_2022:
The predicted CCS values are converted to mobilities of Bruker timsTOF using the Mason Schamp equation.

Thanks,
--Karl

**Comment by GeorgWa** [comment]
Unfortunately, I don't know about the Koina interface to alphaPeptDeep. Maybe my collaegue @jalew188 knows more about this.
When using the library or the gui, alphaPeptDeep provides mobility 1/K0 values by default.
See this tutorial: https://alphapeptdeep.readthedocs.io/en/latest/nbs/tutorial_speclib_from_fasta.html

**Comment by LLautenbacher** [comment]
Hi, I'm the main developer of Koina at the moment. @jalew188 helped me beginning of the year at EUBIC to integrate some AlphaPept models into Koina. 

I had a quick look around the AlphaPept codebase. And to me it looks like this code [here](https://github.com/MannLabs/alphabase/blob/bbaecc380ae157d0f4cc87fffec097ecb7a8ceca/alphabase/peptide/mobility.py#L18) is converting the predicted CCS values to mobility values. 

If you can confirm that this transformation generates the mobility values that @KarlClauser expects I can implement this in Koina as an alternative output.

**Comment by GeorgWa** [comment]
Hi @LLautenbacher ,
Yes this is right. Thank you for implementing this in Koina. I wasn't aware of Koin yet but it looks really cool! I'm looking forward to try it out. 

If this solves the issue I will close it later this week.
