### ISSUE TITLE
Release of Windows GUI

### ISSUE THREAD

**Issue by kostrouc** [MannLabs/alphapeptdeep#118]
Is there an anticipated date for the release of an alphapeptdeep Windows GUI?

The following download link in the README does not work: https://github.com/MannLabs/alphapeptdeep/releases/latest/download/peptdeep_gui_installer_windows.exe

Thank you!

**Comment by jalew188** [comment]
We are working on this issue, we will make a release soon

**Comment by jalew188** [comment]
See #112
