### ISSUE TITLE
Adding mods into AlphaBase

### ISSUE THREAD

**Issue by ehwmatt** [MannLabs/alphapeptdeep#120]
Hi,

I would like to train a model to predict RT/IM for peptides with a custom modification from DDA data (~10,000 modified peptide IDs output from MSFragger into a tsv library). I'm using PeptDeep via the GUI and am able to add my modification into "User-defined modifications" (and have it successfully update in the yaml file). I click to add the mod into AlphaBase but when I go back to the "Transfer" section to set up the training, the modification is not found in the AlphaBase mod search bar. 

Please let me know if I'm misunderstanding the process to train a custom model for DIA library prediction of custom modifications and thanks in advance for any help! 

Matt

**Comment by jalew188** [comment]
Hi @ehwmatt , User-defined modifications will be automatically added into mod list, you don't need "the AlphaBase mod search bar" to add them again.

**Comment by jalew188** [comment]
@ehwmatt Sorry, I have to double check this

> Hi @ehwmatt , User-defined modifications will be automatically added into mod list, you don't need "the AlphaBase mod search bar" to add them again.

**Comment by jalew188** [comment]
Hi @ehwmatt , for transfer learning, it is different as other search engines have different names for the PTMs you are interested. So you need to:
1. Define your PTMs in `User-defined modifications` in AlphaBase format.
2. Define the modification mapping in `Other modification mapping for PSM readers`.

**Comment by jalew188** [comment]
Closed by #125

**Comment by ehwmatt** [comment]
Hi @jalew188,

Thank you for your help with this!! Updating to 1.1.4 solved the first issue I was reported (where any mods I specified weren't shown as custom mods in AlphaBase for the mod mapping).

I still haven't got the GUI working on transfer/library mode but most likely user error I fear! Either way, executing an adapted version of the yaml from #129 from the command line works for trained custom models on my DDA data now and I'm in the process of evaluating the predicted libraries. 

Thanks again! 
Matt
