### ISSUE TITLE
Error in 'peptdeep --install-model'

### ISSUE THREAD

**Issue by hxxhust163** [MannLabs/alphapeptdeep#133]
Hi 

Sorry to bother you.
I have peptdeep installed in my linux system.
when I ran the command 'peptdeep library settings_yaml'. I got an error like this.
![Screenshot from 2024-01-22 20-38-53](https://github.com/MannLabs/alphapeptdeep/assets/66811222/a102722a-fc37-457c-9140-f540c794d43e)

So, I downloaded the 'pretrained_models.zip' manually, and then I ran the command "peptdeep install-models --model-file ./pretrained_models.zip --overwrite True" , I got the same error.

All I did was followed the instructions.
Please help to fix  the problem, thanks very much!

Best 
Xiaoxiang

**Comment by hxxhust163** [comment]
Oh, I fixed this problem by move the 'pretrained_models.zip' into my /home directory. Thanks!

I installed the latest version of peptdeep (1.1.4) and in using peptdeep, I am encountered with two questions.

1. In library prediction using precursor table, I compared the results of two different models, 'generic' and 'hla', which can be selected in the setting.yaml file. But the results of these two model are the same. So, I checked the 'pretrained_models.zip', but  found no hla model. It looks like this:
![Screenshot from 2024-01-24 16-45-59](https://github.com/MannLabs/alphapeptdeep/assets/66811222/7791dc65-eb69-403c-bad1-2fc0fec3d2fd)

I wonder where I can download the hla pretrained model? 

2. Also during the library prediction using precursor table, I ran into two small problems in peptdeep-1.1.4.
One is the keyerror and another one is the warning. Looks like bellow:

![Screenshot from 2024-01-24 16-57-31](https://github.com/MannLabs/alphapeptdeep/assets/66811222/545eb571-0c28-4abd-9eb0-f9db7434571b)

But it was successful in peptdeep-1.0.2 without the error and warning when using the same input precursor table. 
The precursor table is in csv format and looks like this:
![Screenshot from 2024-01-24 17-04-53](https://github.com/MannLabs/alphapeptdeep/assets/66811222/b361b932-4fea-46ad-869a-83237954f5ee)

I also installed the peptdeep-1.1.4 in windows with python3.9. And got the same keyerror and warning.

Please help to figure those out.  Thanks very much!

Best wishes
Xiaoxiang

**Comment by jalew188** [comment]
Yes, HLA and generic models are not trained trained togethor so they are identical.

For KeyError issues, I will test on my own computer

**Comment by hxxhust163** [comment]
OK, thanks! Looking forward for your reply. Maybe there is something wrong in my operation.

Happy snowing! [laugh]
