### ISSUE TITLE
Is it possible to predict 'a, x, c,z' fragment ions?

### ISSUE THREAD

**Issue by hxxhust163** [MannLabs/alphapeptdeep#135]
Hi 

I tried to predict a spectra library by precursor table, and I set the frag_types as 'b,y,a' in setting.yaml. I found the hdf file successfully saved, but translation to tsv failed.  

I wonder if it is possible to  predict 'a, x, c,z' fragment ions in spectra library? If it is.  How can I translate the hdf to tsv? Thanks!

Following is the log:
![Screenshot from 2024-01-29 16-04-49](https://github.com/MannLabs/alphapeptdeep/assets/66811222/185cc4ca-db40-473b-804b-88619acca824)

Best regards
Xiaoxiang

**Comment by jalew188** [comment]
Well, I did not training a model for ExD yet...

**Comment by jalew188** [comment]
It is possible to predict c/z ions using AlphaPeptDeep.
