### ISSUE TITLE
Errors in Transfer

### ISSUE THREAD

**Issue by hxxhust163** [MannLabs/alphapeptdeep#138]
Hi

I used the cmd 'peptdeep transfer setting.yaml' to refine a model for my own data. The params look like this:

![Screenshot from 2024-01-30 15-36-52](https://github.com/MannLabs/alphapeptdeep/assets/66811222/0b7f8671-061f-4581-b780-8ee3241ea051)

I tried two different psm type. One was 'msfragger_pepxml' and another was 'maxquant', but I got two same errors like this: 
![Screenshot from 2024-01-30 15-40-27](https://github.com/MannLabs/alphapeptdeep/assets/66811222/dad9bd79-c5db-48f0-91a8-b6042921152b)

I do not know what is wrong with it.  Could you please help me figure this out?
As you listed in the setting_yaml file 'pfind,diann,speclib_tsv' in psm_type, I wonder if you could provide some example files to show what is the exact columns they contain to be compatible with peptdeep.  

Thanks in advance!

Best regards
Xiaoxiang

**Comment by jalew188** [comment]
It looks like that you are using linux or Windows, so it may be because you did not install mono to read Thermo Raw files

**Comment by hxxhust163** [comment]
Tes, this was done in linux. I also installed peptdeep in windows and run the same cmd as above, but got the same error. And I have installed mono and pythonnet in my linux system.

I want to use the 'speclib_tsv', but I do not know the exact information it contains.

**Comment by jalew188** [comment]
Could you share me the log file?

**Comment by hxxhust163** [comment]
[log.txt](https://github.com/MannLabs/alphapeptdeep/files/14099515/log.txt)

**Comment by jalew188** [comment]
peptdeep version is too old, please reinstall it by `pip install -U peptdeep alphabase alpharaw`

**Comment by hxxhust163** [comment]
I followed your advice and run the command ** pip install -U peptdeep alphabase alpharaw **, but got the same error as above.
Here is the log file. 
[log.txt](https://github.com/MannLabs/alphapeptdeep/files/14106236/log.txt)

**Comment by jalew188** [comment]
Good, now we have some logging information:
`2024-01-31 09:41:28> Loaded 0 PSMs for fragment extraction.`
This means RAW names in msms.txt and your input raw files may be different:
`
psm_df = psm_df[
        psm_df.raw_name.isin(ms2_file_dict)
    ].reset_index(drop=True)

logging.info(f"Loaded {len(psm_df)} PSMs for fragment extraction.")
`
See https://github.com/MannLabs/alphapeptdeep/blob/main/peptdeep/pipeline_api.py#L195

**Comment by jalew188** [comment]
@hxxhust163 Hi, I found this bug (in AlphaRaw), I will fix it soon.

**Comment by jalew188** [comment]
Will be fixed by https://github.com/MannLabs/alpharaw/pull/30/commits/f4ceadb2eb733e132506ed5c8870b6d66268daf1

**Comment by J-Burgess** [comment]
Hi Zeng, hope you are well! 

I had the same error and followed your advice to upgrade `pip install -U alpharaw` to alpharaw version 0.4.3. It gets me a little further but I get the new error that:
Raw file type 'thermo_raw' is not registered in 'ms_reader_provider' 

Please find attached my log: 
[transfer_error.txt](https://github.com/MannLabs/alphapeptdeep/files/14353193/transfer_error.txt)

Thanks!

**Comment by jalew188** [comment]
@J-Burgess Sorry, I forgot to update peptdeep itself... Now it should work

**Comment by J-Burgess** [comment]
Hi @jalew188 thanks I managed to produce new refined models all good!

**Comment by jalew188** [comment]
Great, I close this issue
