### ISSUE TITLE
Generate a library with nonspecific digestion rule?

### ISSUE THREAD

**Issue by cctsou** [MannLabs/alphapeptdeep#144]
I am trying to generate a library using nonspecific digestion rule, the cutting rule I added was 
```
([ARNCEQGHDILKMFPSTWYV])
``` 

Is it correct? I ran it and it has been stuck here for 20 hours with 100% memory usage (140GB), any advice?

```
2024-02-20 16:22:22> xxx/library.tsv does not exist, use default IRT_PEPTIDE_DF to translate irt
2024-02-20 16:22:22> Generating the spectral library ..
```

**Comment by jalew188** [comment]
Due to memory issue in Python, we don't have features for nonspecific digestion.
