### ISSUE TITLE
Does AlphaPeptDeep support pre-digested FASTA files?

### ISSUE THREAD

**Issue by Kokoushin** [MannLabs/alphapeptdeep#164]
Hi,

I have a pre-digested (trypsin) FASTA file and I want to create an in silico library.
I tried using the GUI, but it failed.
Here is my FASTA file.
[diann_001.txt](https://github.com/MannLabs/alphapeptdeep/files/15268898/diann_001.txt)

Best regards,
Ko

**Comment by GeorgWa** [comment]
You can try setting the enzyme to `no-cleave` which should give you full protein peptides.
