### ISSUE TITLE
GUI installer error: doesnt find common_constants.yaml

### ISSUE THREAD

**Issue by JM-Bader** [MannLabs/alphapeptdeep#215]
I tried to install the GUI on a windows machine. 
The installer runs through and opens the command line at the end. 
There, the error appears

![image](https://github.com/user-attachments/assets/606c9dc2-6f69-4f63-9b8c-2355278a5813)

**Comment by JM-Bader** [comment]
I used the peptdeep-1.3.0-windows-amd64.exe

**Comment by mschwoer** [comment]
seems like the alphabase package was not bundled when building the installer
![image](https://github.com/user-attachments/assets/68d2fd98-35a3-467d-b59f-ae60a6ec606c)

**Comment by mschwoer** [comment]
should be fixed by release 1.3.1: https://github.com/MannLabs/alphapeptdeep/releases/tag/v1.3.1
