### ISSUE TITLE
Missing dependencies for nbs

### ISSUE THREAD

**Issue by straussmaximilian** [MannLabs/alphapeptdeep#48]
Hi,
I did install alphapeptdeep locally and tried running some of the Notebooks (test_ccs_rt). 
Here, some dependencies were missing:

- lxml (for reading the results-html with pandas)
- wget (for downloading the files)

wget is in the development requirements. 

As a potential solution, one could do one of the following:
(1) include lxml in the dev requirements and make a note at the beginning of the notebooks that dev needs to be installed
(2) include lxml and wget in the default requirements
(3) Download the additional requirements in the notebooks (!pip install lxml)

**Comment by jalew188** [comment]
Fixed in v0.1.3:
lxml in default req
wget in the notebook
