### ISSUE TITLE
Generic questions about pretrained models

### ISSUE THREAD

**Issue by yangkl96** [MannLabs/alphapeptdeep#55]
Hello,

I have two questions about the pretrained models.

1. Were they only trained on HCD data?
2. Were the "phos" models only trained on ProteomeTools phospho@Y or also phospho@ST? And the other 20 PTMs were not considered in the training?

Thanks,
Kevin

**Comment by jalew188** [comment]
Hi @yangkl96 ,

1. Yes, we only have HCD models currently.
2. In training 'phos' model, we considered a lot of data sets, not only 21 PTMs, but also other regular enriched phospho MS data.
3. 
Best,
Feng
