### ISSUE TITLE
problem of reading pFind.spectra

### ISSUE THREAD

**Issue by ShadoWyyyy** [MannLabs/alphapeptdeep#74]
**Describe the bug**
Hello, I am a student of zhejiang university, after I have read the paper, I want to use it to facilitate better performance of DDA identification of HLA.
but when I use its transfer function to fine tune the model with pFind psm, I met problem like this.
<img width="1080" alt="截屏2023-01-03 20 43 16" src="https://user-images.githubusercontent.com/88261488/210360259-75e518a9-83fe-4c22-b2f4-4f63c1e2c06e.png">

here is my pFind spectra file head 
<img width="1166" alt="截屏2023-01-03 20 50 35" src="https://user-images.githubusercontent.com/88261488/210360659-d36272d6-d8e2-4c77-b2a0-1a75f9222e62.png">

here is my "transfer" parameters in setting.yaml
<img width="457" alt="截屏2023-01-03 20 44 55" src="https://user-images.githubusercontent.com/88261488/210360322-b2d369de-a06f-4b60-bc0c-0c92ff181f98.png">

I am sure I install the it in conda virtual environment successfully because I can use the library function and run it  well.

any idea of how to deal with it would be very appreciated.

**Comment by jalew188** [comment]
Would you please share me the log file (`peptdeep_transfer.log`) in the `model_output_folder`?

Did you use the Installer? or pip? or github code?

**Comment by jalew188** [comment]
It seems that pythonnet is not installed, maybe check https://github.com/MannLabs/alphapeptdeep/tree/development#pip

**Comment by jalew188** [comment]
@ShadoWyyyy Is problem solved?

**Comment by ShadoWyyyy** [comment]
Sorry, there's something wrong with my vpn, so I lost connect for a few days.
Here is my rescore.log, the program seems interrupt almost immediately.
[peptdeep_rescore.log](https://github.com/MannLabs/alphapeptdeep/files/10371362/peptdeep_rescore.log)
I follow the Developer installation instruction and create a conda virtual environment.
I checked the installed package, I have pythonnet
[conda_list_install_package.txt](https://github.com/MannLabs/alphapeptdeep/files/10371371/conda_list_install_package.txt)
Here is the full screenshot of cli when I execute the command line instruction.
<img width="1009" alt="截屏2023-01-09 15 53 38" src="https://user-images.githubusercontent.com/88261488/211261895-aa47212a-d0fe-4cb2-bafa-9018fdcc543c.png">
I can't upload the settings.yaml because github seems doesn't support this file type.

**Comment by ShadoWyyyy** [comment]
And I can run the library function, here is the library.log
[peptdeep_library.log](https://github.com/MannLabs/alphapeptdeep/files/10371435/peptdeep_library.log)
maybe the problem is related to the format of my pFind.spectra file?
[pFind.spectra.txt](https://github.com/MannLabs/alphapeptdeep/files/10371442/pFind.spectra.txt)

**Comment by jalew188** [comment]
This is a bug from pipeline API, I will create a new release version after fix this bug

**Comment by jalew188** [comment]
Sorry, it seems that you are using arm64 (M1 chip) for MacOS. PeptDeep does not support it yet...

**Comment by jalew188** [comment]
Try the latest version? https://github.com/MannLabs/alphapeptdeep/releases/tag/1.0.0. Don't known if it works though

**Comment by ShadoWyyyy** [comment]
> Sorry, it seems that you are using arm64 (M1 chip) for MacOS. PeptDeep does not support it yet...

OK, maybe change to another operating system later and try again, thank you.

**Comment by ShadoWyyyy** [comment]
Hello, I am nowing using the Windows platform, however I still can't use it for HLA DDA rescoring.
Again I use "pip install peptdeep", and everything is OK until I run peptdeep rescore function
There is a part of error logging that turns out to be the same like I reported in this issue before, the screenshot is below
![image](https://user-images.githubusercontent.com/88261488/216534395-890e438e-c747-4d41-94b4-720b05aab677.png)
The full program log is also provided below
[peptdeep_rescore.log](https://github.com/MannLabs/alphapeptdeep/files/10576417/peptdeep_rescore.log)
The settings.yaml is here
[20230203_rescore_settings.txt](https://github.com/MannLabs/alphapeptdeep/files/10576432/20230203_rescore_settings.txt)
The pfind.spectra is here
[20221028_MHC_pFind.spectra.txt](https://github.com/MannLabs/alphapeptdeep/files/10576440/20221028_MHC_pFind.spectra.txt)
I really want to see the performance of this software on rescoring for identification results of traditional search engine, so if you need more information to find the problem, I can provide the data by email for you to test, thanks.

**Comment by jalew188** [comment]
Could you please check pfind's output MGF file instead of RAW?

```
...
ms_file_type: mgf
    ms_file_type_choices:
    - alphapept_hdf
    - thermo_raw
    - mgf
    - mzml
    ms_files: 
    - E:\peptdeep\raw\20221028_MHC_HCDFT.mgf
    - E:\peptdeep\raw\20221111_HCC_387_HCDFT.mgf
    - E:\peptdeep\raw\20221111_HCC_387_HCDFT.mgf
```

**Comment by ShadoWyyyy** [comment]
I change raw to mgf file and here is the rescore.log
[peptdeep_rescore.log](https://github.com/MannLabs/alphapeptdeep/files/10577186/peptdeep_rescore.log)

**Comment by jalew188** [comment]
I will check my own data then

**Comment by ShadoWyyyy** [comment]
> I will check my own data then

OK，looking forward to your reply and solutions

**Comment by jalew188** [comment]
I kind of know what is the issue. Would you please try to rename xxx_HCDFT.mgf to xxx.mgf, it should work this time.

**Comment by jalew188** [comment]
I will support xxx_HCDFT.mgf in the next release.

**Comment by ShadoWyyyy** [comment]
It works, the mgf files are read successfully and transfer learning, but the process end in iteration:
2023-02-06 09:04:53> Require fine-tuning models ...
2023-02-06 09:04:53> Preparing for fine-tuning ...
2023-02-06 09:05:04> Fine-tuning ...
2023-02-06 09:05:04> 1898 PSMs for RT model training/transfer learning
2023-02-06 09:06:29> 3198 PSMs for MS2 model training/transfer learning
2023-02-06 09:08:15> Extracting peptdeep features for 19711 PSMs with multiprocessing ...
2023-02-06 09:09:02> Finished feature extraction with multiprocessing
2023-02-06 09:09:02> [PERC] 3198 target PSMs at 0.01 psm-level FDR
2023-02-06 09:09:02> [PERC] Iteration 1 of Percolator ...
2023-02-06 09:09:02> Traceback (most recent call last):
  File "C:\Users\DELL\.conda\envs\peptdeep\lib\site-packages\peptdeep\pipeline_api.py", line 379, in rescore
    psm_df = percolator.re_score(psm_df)
  File "C:\Users\DELL\.conda\envs\peptdeep\lib\site-packages\peptdeep\rescore\percolator.py", line 460, in re_score
    df = self._cv_score(df)
  File "C:\Users\DELL\.conda\envs\peptdeep\lib\site-packages\peptdeep\rescore\percolator.py", line 375, in _cv_score
    self._train(train_t_df, df_decoy)
  File "C:\Users\DELL\.conda\envs\peptdeep\lib\site-packages\peptdeep\rescore\percolator.py", line 314, in _train
    train_df[self.feature_list].values,
  File "C:\Users\DELL\.conda\envs\peptdeep\lib\site-packages\pandas\core\frame.py", line 3813, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "C:\Users\DELL\.conda\envs\peptdeep\lib\site-packages\pandas\core\indexes\base.py", line 6070, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "C:\Users\DELL\.conda\envs\peptdeep\lib\site-packages\pandas\core\indexes\base.py", line 6133, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['raw_score'] not in index"

I don't understand, because I didn't change anything here, why the raw_score not in index
![image](https://user-images.githubusercontent.com/88261488/216860020-37e925d0-1e46-432f-9da1-c3f4cd964b66.png)
Or should I configure something here in the settings.yaml ?

**Comment by jalew188** [comment]
Just set it as:
```
pfind: []
```

`raw_score` will be ignored

**Comment by ShadoWyyyy** [comment]
> Just set it as:
> 
> ```
> pfind: []
> ```
> 
> `raw_score` will be ignored

Yes, I recognized it and tried again, but the same error still exists.

**Comment by jalew188** [comment]
I see, loading `other_score_columns` happens before loading the yaml file. please go to alphapept_folder/peptdeep/constants/default_settings.yaml, and modify the pfind term as `pfind: {}`.

I will also provide a jupyter notebook. I just tested the notebook and it worked for the RA957 dataset.
[HLA_RA957_DDA_run_AD.zip](https://github.com/MannLabs/alphapeptdeep/files/10661700/HLA_RA957_DDA_run_AD.zip)

**Comment by ShadoWyyyy** [comment]
> I see, loading `other_score_columns` happens before loading the yaml file. please go to alphapept_folder/peptdeep/constants/default_settings.yaml, and modify the pfind term as `pfind: {}`.
> 
> I will also provide a jupyter notebook. I just tested the notebook and it worked for the RA957 dataset. [HLA_RA957_DDA_run_AD.zip](https://github.com/MannLabs/alphapeptdeep/files/10661700/HLA_RA957_DDA_run_AD.zip)
> 
> ------ edited ------- For the notebook, you don't need to modify yaml files

ok, Thanks, I will follow the instruction.
