### ISSUE TITLE
how to know syntax for modifcations other than phophorylation and oxidation?

### ISSUE THREAD

**Issue by gsaxena888** [MannLabs/alphapeptdeep#77]
If I want to create a library with less common modifications (eg acetylation, methylation, citrulination etc.), is there some documentation or file which indicates which modifications are supported and their syntax?

**Comment by jalew188** [comment]
We used the syntax mod_name@site. The modification names and sites are from UniMod, such as Dimethyl@Any N-term, GG@K, Acetyl@Protein N-term, ... Check https://github.com/MannLabs/alphabase/blob/main/alphabase/constants/const_files/modification.tsv.

If you have modifications those are not in UniMod, you can easily add them into AlphaBase/PeptDeep, check https://github.com/MannLabs/alphapeptdeep/blob/main/peptdeep/constants/default_settings.yaml#L41

**Comment by jalew188** [comment]
You can also easily add UniMod modifications from the GUI. We will make it easier in v1.0.0
