### ISSUE TITLE
Some library entries don't get translated to a tsv file

### ISSUE THREAD

**Issue by gsaxena888** [MannLabs/alphapeptdeep#91]
Attached is an input file and settings.yaml file that if run, will *not* generate a .tsv output file (though it will generate the .hdf5 file). Thoughts? (I used alphapeptdeep 1.0.1, i.e., the latest version)

[settingsLibrary.yaml.gz](https://github.com/MannLabs/alphapeptdeep/files/10761985/settingsLibrary.yaml.gz)
[first_search.mzid_forPred.tsv.gz](https://github.com/MannLabs/alphapeptdeep/files/10762059/first_search.mzid_forPred.tsv.gz)

**Comment by jalew188** [comment]
Check here https://github.com/MannLabs/alphapeptdeep/blob/main/peptdeep/constants/default_settings.yaml#L268

**Comment by gsaxena888** [comment]
[peptdeep_library.log](https://github.com/MannLabs/alphapeptdeep/files/10767033/peptdeep_library.log)

I just tried with the setting to "true" for translate_mod_to_unimod_id. It did *NOT* make a difference. I've attached the log above.

**Comment by jalew188** [comment]
That is wired, I can generate the tsv based on your input file... Maybe because I used the latest version (1.0.2)
