### ISSUE TITLE
CANNOT loading PSMs and extracting fragments for transfer learning

### ISSUE THREAD

**Issue by qazq1** [MannLabs/alphapeptdeep#93]
When I use the 'Transfer' section to get a re-fined model, something wrong with  'Loading PSMs and extracting fragments' happened. I provided the paths of MaxQuant data 'msms.txt' and the corresponding raw file, but got an error.
[peptdeep_transfer.log](https://github.com/MannLabs/alphapeptdeep/files/10778689/peptdeep_transfer.log)

**Comment by jalew188** [comment]
Can you also share the settings.yaml file?
