### ISSUE TITLE
Transfer of alphapeptdeep predicted HLA library to DIANN and test with acquired raw files (from Q Exactive™ HF-X mass spectrometer): precursor matrix is blank

### ISSUE THREAD

**Issue by marthanik** [MannLabs/alphapeptdeep#96]
Hello,

we ultimately generated an HLA-library using PeptDeep-HLA for the prediction of peptides and alphapeptdeep for library generation and conversion to .tsv for compatibility with DIANN. The file was readable with DIANN and we used it with some already acquired sample spectra to test for peptide identification. Despite the fact that the test.log file mentions identified IDs at the 1% FDR for both tested sample spectra after the second pass, eventualy the pr_matrix.tsv is empty. Any idea why this might be happening? Could you maybe provide us with the exact options enabled in DIANN?

Best,
Martha

[test.log.txt](https://github.com/MannLabs/alphapeptdeep/files/11342769/test.log.txt)

**Comment by jalew188** [comment]
Thanks @marthanik. Maybe it is better to test the data by BigLib from this paper: https://www.mcponline.org/article/S1535-9476(21)00053-0/fulltext. We also use the pan library to test our data if something did not go well.
